server:
  port: 8001

mybatis:
  type-aliases-package: com.roc.sapi.pojo
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml

spring:
  application:
    name: s-provider

  datasource:
    url: jdbc:mysql://localhost:3306/Db01?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver

